clear all
close all
row = 3264;
col = 2448;
% imagename='C8490_Shading_Bright_15fps.raw'; 
imagename1='./1.raw'; 
imagename2='./2.raw'; 
fid1 = fopen(imagename1,'r');
A=fread(fid1,[row col],'uint16=>double');
A=A'; 
fclose(fid1);
fid2 = fopen(imagename2,'r');
B=fread(fid1,[row col],'uint16=>double');
B=B'; 
fclose(fid2);
img1=A;
img2=B;
A_demosaic = demosaic(uint16(img1),'bggr');
B_demosaic = demosaic(uint16(img2),'bggr');
tempA = double(A_demosaic);
tempB = double(B_demosaic);
final_results = uint8(tempA/1023*255);
D=grayworld(final_results);
final_results_awb(:,:,1) = final_results(:,:,1)*D(1);
final_results_awb(:,:,3) = final_results(:,:,3)*D(3);
final_results_awb(:,:,2) = final_results(:,:,2);
% imwrite(final_results_awb,'1_awb.bmp');
gauss_final_results_awb = imgaussfilt(final_results_awb,6);
lab_A = rgb2lab(double(gauss_final_results_awb)/255);
lab = lab_A;
color_a = lab(:,:,2);
color_l = lab(:,:,1);
color_b = lab(:,:,3);
% figure,imshow(color_a*10,[-128 128]);
[h,w]=size(color_a);
color_a_left_bottom = 10*color_a(h/2:end,1:w/2);
color_l_left_bottom = color_l(h/2:end,1:w/2);
color_b_left_bottom = 10*color_b(h/2:end,1:w/2);
figure,imshow(color_a_left_bottom,[-128 128]),title('1_a');
figure,imshow(color_b_left_bottom,[-128 128]),title('1_b');
figure,imshow(color_l_left_bottom*2,[0 100]),title('1_l');
%%
final_results = uint8(tempB/1023*255);
D=grayworld(final_results);
final_results_awb(:,:,1) = final_results(:,:,1)*D(1);
final_results_awb(:,:,3) = final_results(:,:,3)*D(3);
final_results_awb(:,:,2) = final_results(:,:,2);
% imwrite(final_results_awb,'1_awb.bmp');
gauss_final_results_awb = imgaussfilt(final_results_awb,6);
lab_B = rgb2lab(double(gauss_final_results_awb)/255);
lab = lab_B;
color_a = lab(:,:,2);
color_l = lab(:,:,1);
color_b = lab(:,:,3);
% figure,imshow(color_a*10,[-128 128]);
[h,w]=size(color_a);
color_a_left_bottom = 10*color_a(h/2:end,1:w/2);
[h_part,w_part]=size(color_a_left_bottom);
color_l_left_bottom = color_l(h/2:end,1:w/2);
color_b_left_bottom = 10*color_b(h/2:end,1:w/2);
figure,imshow(color_a_left_bottom,[-128 128]),title('1_a');
figure,imshow(color_b_left_bottom,[-128 128]),title('1_b');
figure,imshow(color_l_left_bottom*2,[0 100]),title('1_l');